on: [push, pull_request]
name: lint
jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup show && rustup update && rustup component add rustfmt
      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup show && rustup update && rustup component add clippy
      - name: cargo clippy
        run: cargo clippy --workspace --all-features --tests -- -D warnings

  readme:
    name: cargo readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo +stable install cargo-readme
      - run: cargo readme > README.md && git diff --exit-code

  check-spdx-headers:
    name: spdx check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: enarx/spdx@master
        with:
          licenses: Apache-2.0
